pygments: true
permalink: /:categories/:title
url: https://ahornstudio.github.io/amateur-unconcern
markdown: kramdown
main_title: "Amateur Unconcern. A Photo-Literary Fantasia. By the Photocaptionist"
include: [a, c, j]
excerpt_separator: ""
safe: false
navigation:
- text: Title
  url: "{{ site.baseurl }}/"
- text: Intro
  url: "{{ site.baseurl }}/intro"- text: Act I
  url: /act1
- text: Act II
  url: /act2
- text: Act III
  url: /act3
- text: Act IV
  url: /act4
- text: Act V
  url: /act5
- text: Credits
  url: /credits
- text: Press
  url: /press

baseurl: "/amateur-unconcern"
